apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
  namespace: _{_NAMESPACE_}_
  labels:
    app: solar-system
spec:
  replicas: _{_REPLICAS_}_
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        - name: solar-system
          image: _{_IMAGE_}_
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: mongo-db-creds
